export interface Currency {
  currencyCode: string,
  name: string
}

export const currencies: Currency[] = [
  {"currencyCode": "AED", "name": "UAE dirham"},
  {"currencyCode": "AFN", "name": "Afghan afghani"},
  {"currencyCode": "ALL", "name": "Albanian lek"},
  {"currencyCode": "AMD", "name": "Armenian dram"},
  {"currencyCode": "ANG", "name": "Netherlands Antillean gulden"},
  {"currencyCode": "AOA", "name": "Angolan kwanza"},
  {"currencyCode": "ARS", "name": "Argentine peso"},
  {"currencyCode": "AUD", "name": "Australian dollar"},
  {"currencyCode": "AWG", "name": "Aruban florin"},
  {"currencyCode": "AZN", "name": "Azerbaijani manat"},
  {"currencyCode": "BAM", "name": "Bosnia and Herzegovina konvertibilna marka"},
  {"currencyCode": "BBD", "name": "Barbadian dollar"},
  {"currencyCode": "BDT", "name": "Bangladeshi taka"},
  {"currencyCode": "BGN", "name": "Bulgarian lev"},
  {"currencyCode": "BHD", "name": "Bahraini dinar"},
  {"currencyCode": "BIF", "name": "Burundi franc"},
  {"currencyCode": "BMD", "name": "Bermudian dollar"},
  {"currencyCode": "BND", "name": "Brunei dollar"},
  {"currencyCode": "BOB", "name": "Bolivian boliviano"},
  {"currencyCode": "BRL", "name": "Brazilian real"},
  {"currencyCode": "BSD", "name": "Bahamian dollar"},
  {"currencyCode": "BTN", "name": "Bhutanese ngultrum"},
  {"currencyCode": "BWP", "name": "Botswana pula"},
  {"currencyCode": "BYR", "name": "Belarusian ruble"},
  {"currencyCode": "BZD", "name": "Belize dollar"},
  {"currencyCode": "CAD", "name": "Canadian dollar"},
  {"currencyCode": "CDF", "name": "Congolese franc"},
  {"currencyCode": "CHF", "name": "Swiss franc"},
  {"currencyCode": "CLP", "name": "Chilean peso"},
  {"currencyCode": "CNY", "name": "Chinese/Yuan renminbi"},
  {"currencyCode": "COP", "name": "Colombian peso"},
  {"currencyCode": "CRC", "name": "Costa Rican colon"},
  {"currencyCode": "CUC", "name": "Cuban peso"},
  {"currencyCode": "CVE", "name": "Cape Verdean escudo"},
  {"currencyCode": "CZK", "name": "Czech koruna"},
  {"currencyCode": "DJF", "name": "Djiboutian franc"},
  {"currencyCode": "DKK", "name": "Danish krone"},
  {"currencyCode": "DOP", "name": "Dominican peso"},
  {"currencyCode": "DZD", "name": "Algerian dinar"},
  {"currencyCode": "EEK", "name": "Estonian kroon"},
  {"currencyCode": "EGP", "name": "Egyptian pound"},
  {"currencyCode": "ERN", "name": "Eritrean nakfa"},
  {"currencyCode": "ETB", "name": "Ethiopian birr"},
  {"currencyCode": "EUR", "name": "European Euro"},
  {"currencyCode": "FJD", "name": "Fijian dollar"},
  {"currencyCode": "FKP", "name": "Falkland Islands pound"},
  {"currencyCode": "GBP", "name": "British pound"},
  {"currencyCode": "GEL", "name": "Georgian lari"},
  {"currencyCode": "GHS", "name": "Ghanaian cedi"},
  {"currencyCode": "GIP", "name": "Gibraltar pound"},
  {"currencyCode": "GMD", "name": "Gambian dalasi"},
  {"currencyCode": "GNF", "name": "Guinean franc"},
  {"currencyCode": "GQE", "name": "Central African CFA franc"},
  {"currencyCode": "GTQ", "name": "Guatemalan quetzal"},
  {"currencyCode": "GYD", "name": "Guyanese dollar"},
  {"currencyCode": "HKD", "name": "Hong Kong dollar"},
  {"currencyCode": "HNL", "name": "Honduran lempira"},
  {"currencyCode": "HRK", "name": "Croatian kuna"},
  {"currencyCode": "HTG", "name": "Haitian gourde"},
  {"currencyCode": "HUF", "name": "Hungarian forint"},
  {"currencyCode": "IDR", "name": "Indonesian rupiah"},
  {"currencyCode": "ILS", "name": "Israeli new sheqel"},
  {"currencyCode": "INR", "name": "Indian rupee"},
  {"currencyCode": "IQD", "name": "Iraqi dinar"},
  {"currencyCode": "IRR", "name": "Iranian rial"},
  {"currencyCode": "ISK", "name": "Icelandic kr\u00f3na"},
  {"currencyCode": "JMD", "name": "Jamaican dollar"},
  {"currencyCode": "JOD", "name": "Jordanian dinar"},
  {"currencyCode": "JPY", "name": "Japanese yen"},
  {"currencyCode": "KES", "name": "Kenyan shilling"},
  {"currencyCode": "KGS", "name": "Kyrgyzstani som"},
  {"currencyCode": "KHR", "name": "Cambodian riel"},
  {"currencyCode": "KMF", "name": "Comorian franc"},
  {"currencyCode": "KPW", "name": "North Korean won"},
  {"currencyCode": "KRW", "name": "South Korean won"},
  {"currencyCode": "KWD", "name": "Kuwaiti dinar"},
  {"currencyCode": "KYD", "name": "Cayman Islands dollar"},
  {"currencyCode": "KZT", "name": "Kazakhstani tenge"},
  {"currencyCode": "LAK", "name": "Lao kip"},
  {"currencyCode": "LBP", "name": "Lebanese lira"},
  {"currencyCode": "LKR", "name": "Sri Lankan rupee"},
  {"currencyCode": "LRD", "name": "Liberian dollar"},
  {"currencyCode": "LSL", "name": "Lesotho loti"},
  {"currencyCode": "LTL", "name": "Lithuanian litas"},
  {"currencyCode": "LVL", "name": "Latvian lats"},
  {"currencyCode": "LYD", "name": "Libyan dinar"},
  {"currencyCode": "MAD", "name": "MorocurrencyCodean dirham"},
  {"currencyCode": "MDL", "name": "Moldovan leu"},
  {"currencyCode": "MGA", "name": "Malagasy ariary"},
  {"currencyCode": "MKD", "name": "Macedonian denar"},
  {"currencyCode": "MMK", "name": "Myanma kyat"},
  {"currencyCode": "MNT", "name": "Mongolian tugrik"},
  {"currencyCode": "MOP", "name": "Macanese pataca"},
  {"currencyCode": "MRO", "name": "Mauritanian ouguiya"},
  {"currencyCode": "MUR", "name": "Mauritian rupee"},
  {"currencyCode": "MVR", "name": "Maldivian rufiyaa"},
  {"currencyCode": "MWK", "name": "Malawian kwacha"},
  {"currencyCode": "MXN", "name": "Mexican peso"},
  {"currencyCode": "MYR", "name": "Malaysian ringgit"},
  {"currencyCode": "MZM", "name": "Mozambican metical"},
  {"currencyCode": "NAD", "name": "Namibian dollar"},
  {"currencyCode": "NGN", "name": "Nigerian naira"},
  {"currencyCode": "NIO", "name": "Nicaraguan c\u00f3rdoba"},
  {"currencyCode": "NOK", "name": "Norwegian krone"},
  {"currencyCode": "NPR", "name": "Nepalese rupee"},
  {"currencyCode": "NZD", "name": "New Zealand dollar"},
  {"currencyCode": "OMR", "name": "Omani rial"},
  {"currencyCode": "PAB", "name": "Panamanian balboa"},
  {"currencyCode": "PEN", "name": "Peruvian nuevo sol"},
  {"currencyCode": "PGK", "name": "Papua New Guinean kina"},
  {"currencyCode": "PHP", "name": "Philippine peso"},
  {"currencyCode": "PKR", "name": "Pakistani rupee"},
  {"currencyCode": "PLN", "name": "Polish zloty"},
  {"currencyCode": "PYG", "name": "Paraguayan guarani"},
  {"currencyCode": "QAR", "name": "Qatari riyal"},
  {"currencyCode": "RON", "name": "Romanian leu"},
  {"currencyCode": "RSD", "name": "Serbian dinar"},
  {"currencyCode": "RUB", "name": "Russian ruble"},
  {"currencyCode": "SAR", "name": "Saudi riyal"},
  {"currencyCode": "SBD", "name": "Solomon Islands dollar"},
  {"currencyCode": "SCR", "name": "Seychellois rupee"},
  {"currencyCode": "SDG", "name": "Sudanese pound"},
  {"currencyCode": "SEK", "name": "Swedish krona"},
  {"currencyCode": "SGD", "name": "Singapore dollar"},
  {"currencyCode": "SHP", "name": "Saint Helena pound"},
  {"currencyCode": "SLL", "name": "Sierra Leonean leone"},
  {"currencyCode": "SOS", "name": "Somali shilling"},
  {"currencyCode": "SRD", "name": "Surinamese dollar"},
  {"currencyCode": "SYP", "name": "Syrian pound"},
  {"currencyCode": "SZL", "name": "Swazi lilangeni"},
  {"currencyCode": "THB", "name": "Thai baht"},
  {"currencyCode": "TJS", "name": "Tajikistani somoni"},
  {"currencyCode": "TMT", "name": "Turkmen manat"},
  {"currencyCode": "TND", "name": "Tunisian dinar"},
  {"currencyCode": "TRY", "name": "Turkish new lira"},
  {"currencyCode": "TTD", "name": "Trinidad and Tobago dollar"},
  {"currencyCode": "TWD", "name": "New Taiwan dollar"},
  {"currencyCode": "TZS", "name": "Tanzanian shilling"},
  {"currencyCode": "UAH", "name": "Ukrainian hryvnia"},
  {"currencyCode": "UGX", "name": "Ugandan shilling"},
  {"currencyCode": "USD", "name": "United States dollar"},
  {"currencyCode": "UYU", "name": "Uruguayan peso"},
  {"currencyCode": "UZS", "name": "Uzbekistani som"},
  {"currencyCode": "VEB", "name": "Venezuelan bolivar"},
  {"currencyCode": "VND", "name": "Vietnamese dong"},
  {"currencyCode": "VUV", "name": "Vanuatu vatu"},
  {"currencyCode": "WST", "name": "Samoan tala"},
  {"currencyCode": "XAF", "name": "Central African CFA franc"},
  {"currencyCode": "XCD", "name": "East Caribbean dollar"},
  {"currencyCode": "XDR", "name": "Special Drawing Rights"},
  {"currencyCode": "XOF", "name": "West African CFA franc"},
  {"currencyCode": "XPF", "name": "CFP franc"},
  {"currencyCode": "YER", "name": "Yemeni rial"},
  {"currencyCode": "ZAR", "name": "South African rand"},
  {"currencyCode": "ZMK", "name": "Zambian kwacha"},
  {"currencyCode": "ZWR", "name": "Zimbabwean dollar"}
]
